Default constsr
Veridise/yul2llvm pull request #100
Opened 2023-05-09 22:05 UTC by veriAjinkya

Adds capability for default constructors when explicityly not defined in solidity
Removes self argument from constructors (which was perviously added to avoid branching in arg and ret memory allocation code)

2023-05-09 22:46 UTC, Technius requested changes
The test cases needs to check that the actual constructor LLVM function is defined (not just declared). Right now they only check its call site.

Please also add a test case for implicit constructor in an inherited contract.

2023-05-09 22:46 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/FunctionDeclaratorVisitor.cpp
> +      addself = false;
```suggestion
    const bool addself = !isConstructor(functionName);
```

2023-05-09 23:40 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/FunctionDeclaratorVisitor.cpp
> +      addself = false;
done

2023-05-10 01:09 UTC, Technius approved these changes

2023-05-10 21:24 UTC, merged