Aj/sload
Veridise/yul2llvm pull request #102
Opened 2023-05-12 22:12 UTC by veriAjinkya

1. Load type of sload is now inferred from pointer instead of assumed to be fixed
2. In json object describing the struct type, key field now referes to array of members (previously it was a nested object, with each field name as key and its description as a object)
        This is required for traversing the fields in order they appear, else the sequence of fields gets screwed up and therefore distances
3. Fixed distance calculation for byte offset to field index.

2023-05-13 02:15 UTC, Technius reviewed
Waiting for #101 to be merged before I review this further.

2023-05-13 02:15 UTC, Technius commented on src/pyul/preprocess.py
> +                    ],
Please also update the part of the readme that describes the metadata format.

2023-05-15 19:20 UTC, Technius requested changes
This needs a test case that checks the logic in this PR.

2023-05-15 19:20 UTC, Technius commented on lib/include/libYulAST/YulConstants.h
> +const static std::string COPY_STRUCT_TO_STOTRAGE_REGEX_LIT =
```suggestion
const static std::string COPY_STRUCT_TO_STORAGE_REGEX_LIT =
```

2023-05-15 19:20 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicEmitter.cpp
> +    llvm::errs() << "Source pointer not a pointer to storage struct";
This seems to check the dest pointer. The source pointer is not checked.

2023-05-22 22:59 UTC, veriAjinkya commented on lib/include/libYulAST/YulConstants.h
> +const static std::string COPY_STRUCT_TO_STOTRAGE_REGEX_LIT =
done

2023-05-22 23:02 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicEmitter.cpp
> +    llvm::errs() << "Source pointer not a pointer to storage struct";
added checks

2023-05-22 23:05 UTC, veriAjinkya commented on src/pyul/preprocess.py
> +                    ],
done

2023-05-23 00:10 UTC, Technius approved these changes
LGTM contingent on a test case for this PR

2023-05-23 00:17 UTC, veriAjinkya commented
Tkt created for the PR so we dont miss out on it

2023-05-23 00:17 UTC, merged