Ajinkya/asan
Veridise/yul2llvm pull request #53
Opened 2022-11-08 14:16 UTC by veriAjinkya

This is supposed to be merged after #52.

2022-11-08 21:47 UTC, Technius commented on CMakeLists.txt
> +
This should check `CMAKE_BUILD_TYPE`. Furthermore, asan is both a compile time flag and a library to link against, so we need:
```cmake
add_compile_options(-fsanitize=address)
add_link_options(-fsanitize=address)
```

2022-11-08 21:47 UTC, Technius commented
Didn't look at the whole thing yet since it seems to be mixed with the other PR.

2022-11-09 22:12 UTC, veriAjinkya commented on CMakeLists.txt
> +
done

2022-11-09 22:21 UTC, Technius requested changes

2022-11-09 22:32 UTC, veriAjinkya commented on flake.nix
> +            ASAN_OPTIONS=detect_leaks=0 PATH="$out"/bin:"$PATH" lit ./tests -v
Its a nix string literal, how prepend last line of it?

2022-11-09 22:34 UTC, Technius commented on flake.nix
> +            ASAN_OPTIONS=detect_leaks=0 PATH="$out"/bin:"$PATH" lit ./tests -v
You can use `+` for string concat, e.g.:
```nix
checkPhase = ''
  export ASAN_OPTIONS=detect_leaks=0
'' + ''
  echo hi
'';
```

2022-11-09 22:40 UTC, veriAjinkya commented on flake.nix
> +            ASAN_OPTIONS=detect_leaks=0 PATH="$out"/bin:"$PATH" lit ./tests -v
done

2022-11-09 22:41 UTC, veriAjinkya commented on CMakeLists.txt
> +  add_link_options(-fsanitize=address)
It doesn't work on mac.

2022-11-09 22:43 UTC, veriAjinkya commented on flake.nix
> +          propagatedBuildInputs = [ final.solc_0_8_15 final.yul2llvm_cpp_dbg ];
This line adds yul2llvm_cpp_dbg instead of yul2llvm_cpp

2022-11-09 22:43 UTC, veriAjinkya commented on flake.nix
> +          propagatedBuildInputs = [ final.solc_0_8_15 final.yul2llvm_cpp_dbg ];
Pushed that explicitly makes this replacement

2022-11-09 22:48 UTC, Technius commented on CMakeLists.txt
> +  add_link_options(-fsanitize=address)
Should use `option` to explicitly declare the option: https://cmake.org/cmake/help/latest/command/option.html

2022-11-10 18:20 UTC, Technius approved these changes

2022-11-10 21:01 UTC, merged