Aj/structs
Veridise/yul2llvm pull request #63
Opened 2022-12-02 14:14 UTC by veriAjinkya

Adds support for translating solidity structs.

2022-12-05 21:49 UTC, Technius requested changes

2022-12-05 21:49 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +    auto test = [](llvm::Instruction *inst)->bool {
This is duplicated below. Should be extracted into a helper function like `isAddWithConstantArgs(llvm::Instruction *inst)`

2022-12-05 21:49 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +          assert(false && "folding happening at wrong location");
What is the assumption being made about the "location" at which the fold occurs?

2022-12-05 21:49 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +    assert(false && "Folding staring from wrong instruction");
```suggestion
    assert(false && "Folding staring from operation that is not addition of two constants");
```

2022-12-06 18:35 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  std::string getNameFromNamePath(std::vector<std::string> namePath);
done

2022-12-06 18:40 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +  assert(false && "field member not found");
done, but also, kept the assert as a run time error

2022-12-06 18:41 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +int YulContractNode::getFieldIndexInStruct(TypeInfo ti, std::string name){
done

2022-12-16 16:52 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +  int index;
This will get replaced once memory structs are implemented

2022-12-16 16:54 UTC, veriAjinkya commented on lib/include/libYulAST/YulContractNode.h
> +  std::vector<std::string> getNamePathBySlotOffset(int slot, int offset);
done

2022-12-16 17:23 UTC, veriAjinkya commented on lib/include/libYulAST/YulContractNode.h
> +  std::string typeStr;
done

2022-12-16 17:24 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +  for(auto name: namePath){
done

2022-12-16 17:26 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +          assert(false && "folding happening at wrong location");
Assumption: During folding, all the adds should have strictly one constant and one value computed above. 
Updated error message to reflect that

2022-12-16 17:27 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +    assert(false && "Folding staring from wrong instruction");
addressed above

2022-12-16 18:55 UTC, Technius requested changes

2022-12-16 18:55 UTC, Technius commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  llvm::Value *getPointerToStorageVarByName(std::vector<std::string>,
Should document why this takes a vector of strings (storage var + field names?). Also, this appears to assume that the vector is not empty.

2022-12-16 18:55 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/CodegenVisitor.cpp
> +      getModule(), structTypes["self"]->getPointerTo(STORAGE_ADDR_SPACE), false,
It would be better to use `getSelfType()` instead of `structTypes["self"]`, in case we want to refactor how the self type is created in the future.
```suggestion
      getModule(), getSelfType()->getPointerTo(STORAGE_ADDR_SPACE), false,
```

2022-12-16 18:55 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/CodegenVisitor.cpp
> +          structTypes["self"]->getPointerTo(STORAGE_ADDR_SPACE)),
same here

2022-12-16 18:55 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicHelper.cpp
> +YulIntrinsicHelper::getNameFromNamePath(std::vector<std::string> namePath) {
Should assert that `namePath` is nonempty

2022-12-16 18:55 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +    }
This snippet starting from the `auto test = ...` is duplicated from `rewriteStorageOffsetLoadIntrinsic`. Can this be refactored into a helper function?

2022-12-16 18:55 UTC, Technius commented on tests/e2e/feature/structs/struct-mem-alias.sol
> +//CHECK: %word_arr_load = zext i32
should also check for `}` or else the above lines might match code in a different function

2022-12-16 18:57 UTC, Technius commented on lib/libYulAST/YulContractNode.cpp
> +  return INT_MAX;
Would be better to use `std::numeric_limits` from `<limits>`
```suggestion
  return std::numeric_limits<int>::max();
```

2022-12-16 18:59 UTC, Technius commented on lib/libYulAST/YulContractNode.cpp
> +  }
nit: this could be simplified using `std::find_if` and `std::distance`.

```c++
auto it = std::find_if(ti.members.begin(), ti.members.end(), [&](auto &mem) { return name == mem.name; });
if (it != mem.end()) {
  return std::distance(mem.begin(), it);
} else {
  // not found
  // ...
}
```

2022-12-17 00:11 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  llvm::Value *getPointerToStorageVarByName(std::vector<std::string>,
done

2022-12-17 00:33 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/CodegenVisitor.cpp
> +      getModule(), structTypes["self"]->getPointerTo(STORAGE_ADDR_SPACE), false,
done

2022-12-17 00:35 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/CodegenVisitor.cpp
> +          structTypes["self"]->getPointerTo(STORAGE_ADDR_SPACE)),
done

2022-12-17 00:37 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  llvm::Value *getPointerToStorageVarByName(std::vector<std::string>,
yes, it assumes that there is atleast one name in the vector (while accessing non struct vars)

2022-12-17 00:38 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicHelper.cpp
> +YulIntrinsicHelper::getNameFromNamePath(std::vector<std::string> namePath) {
done

2022-12-17 00:43 UTC, veriAjinkya commented on tests/e2e/feature/structs/struct-mem-alias.sol
> +//CHECK: %word_arr_load = zext i32
done

2022-12-17 00:43 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +  return INT_MAX;
done

2022-12-17 00:46 UTC, veriAjinkya commented on lib/libYulAST/YulContractNode.cpp
> +  }
done

2022-12-17 01:15 UTC, Technius approved these changes
LGTM. Probably better to get the rest of the changes stacked on top checked in before we do a full review.

2022-12-17 01:34 UTC, merged