Aj/typesys2
Veridise/yul2llvm pull request #91
Opened 2023-02-08 01:29 UTC by veriAjinkya

This is the second pr following PR typesys1. 
Adds the following 
* A function signature visitor that visits each function and builds its signature
* LLVM now uses this new type system to get function types for declaring functions
* Adds parsing of types from abi

2023-02-09 03:27 UTC, Technius requested changes
Did my first pass over the code. I have a lot of questions.

2023-02-09 03:27 UTC, Technius commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +      }
```suggestion
      assert(retType && "Could not infer type of the return variable ");
```

2023-02-09 03:27 UTC, Technius commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +  std::vector<YulType *> types{typeContext.lookupType("t_uint8")};
Why is this only a single uint8? Shouldn't this be like the Yul equivalent of a pointer to/array of uint8?

2023-02-09 03:27 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/FunctionDeclaratorVisitor.cpp
> +                                             YulAddressSpace::DEFAULT));
What happens if the address space of the argument is memory or pointer?

2023-02-09 03:27 UTC, Technius commented on lib/libyul2llvm/YulASTVisitor/FunctionDefinitionHelper.cpp
> +    }
I really do not like how complex this solution is. Can we do something simpler like inserting a return instruction if the block does not have a terminator yet?

2023-02-09 03:27 UTC, Technius commented on lib/libYulAST/Types/YulTypeContext.cpp
> +  auto metadataExternalFunctions = contract.at("metadata").at("external_fns");
This isn't used.

2023-02-09 14:44 UTC, veriAjinkya commented on src/pyul/utils/YulAntlr/Yul.g4
> -// Define a grammar called Yul
it was a stray copy. the original file is in src/pyul/utils. the one deleted is in utils/yul.g4

2023-02-09 14:46 UTC, veriAjinkya commented on tests/e2e/hello-multifile copy.txt
> +RUN: pyul %S/Inputs/hello-multifile/MainContract.sol -o %t --project-dir %S/Inputs/hello-multifile
moved it to inheritance branch

2023-02-09 14:50 UTC, veriAjinkya commented on lib/libYulAST/IntrinsicPatterns.cpp
> +  assert(match_success && "Yul struct type did not match regex");
I changed the pattern later. This is a previous pattern. Changed all of them to new pattern

2023-02-09 14:50 UTC, veriAjinkya commented on lib/libYulAST/Types/YulTypeContext.cpp
> +  typeName2YulType[typeStr] = std::move(type);
yes, I am representing bools using t_uint1

2023-02-14 23:28 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulTypeContext.h
> +  bool parseStructFromAbiArg(const nlohmann::json &arg, std::string name);
This needs to be converted to strings inside the called function anyway

2023-02-14 23:31 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulTypeContext.h
> +  std::string cleanupTypeName(std::string typeStr);
done

2023-02-14 23:31 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulTypeContext.h
> +  std::string convertAbiTypeNameToStorageLayoutName(std::string);
has to be converted to string anyway for pattern matcher

2023-02-14 23:34 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicHelper.cpp
> +    return llvm::ArrayType::get(elementType, 0);
This is outdated. Solved in latest push

2023-02-14 23:35 UTC, veriAjinkya commented on lib/include/libYulAST/Utils/StringHelper.h
> +bool startsWith(std::string name, std::string prefix);
done

2023-02-14 23:37 UTC, veriAjinkya commented on lib/libYulAST/IntrinsicPatterns.cpp
> +  std::regex regex(ARRAY_TYPE_REGEX_LIT);
done

2023-02-14 23:39 UTC, veriAjinkya commented on lib/libYulAST/Types/YulTypeContext.cpp
> +    typeStr = "t_string";
according to old type system, will be fixed when we handle type in typesys2

2023-02-14 23:40 UTC, veriAjinkya commented on lib/libYulAST/Types/YulTypeContext.cpp
> +    std::abort();
The compiler does compile with warning

2023-02-14 23:47 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/CodegenVisitor.cpp
> +    builder = Builder.get();
this function is called from places couple of places
1. from intrinisic rewrite: In this case yes, callinst is assumed to be non null
2. from return nodes handling: In this case we are not rewriting any call and want to emit the packing instructions using the default, module builder

2023-02-14 23:49 UTC, veriAjinkya commented on tests/e2e/Inputs/inheritance/base.sol
> +pragma solidity ^0.8.10;
For now yes

2023-02-14 23:50 UTC, veriAjinkya commented on pyproject.toml
> +antlr4-tools = "0.2"
removed

2023-02-14 23:51 UTC, veriAjinkya commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +      }
this would cause the assert to get removed in release builds, so we shifted to if(err) std::abort pattern.

2023-02-14 23:53 UTC, veriAjinkya commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +  std::vector<YulType *> types{typeContext.lookupType("t_uint8")};
String literals not completely handled. This is place holder. The testcases are xfailed to make sure we handle it

2023-02-14 23:54 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/FunctionDeclaratorVisitor.cpp
> +                                             YulAddressSpace::DEFAULT));
fixed

2023-02-14 23:55 UTC, veriAjinkya commented on lib/libYulAST/Types/YulTypeContext.cpp
> +  auto metadataExternalFunctions = contract.at("metadata").at("external_fns");
removed

2023-02-14 23:56 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulFunctionSignature.h
> +  std::string to_string() {
done

2023-02-14 23:56 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulType.h
> +  virtual std::string to_string() { return typeStr; }
done

2023-02-14 23:56 UTC, veriAjinkya commented on lib/include/libYulAST/Types/YulFunctionSignature.h
> +      string += it->to_string();
done

2023-02-14 23:57 UTC, veriAjinkya commented on lib/include/libYulAST/Utils/ScopedSymbolTable.h
> +  std::string to_string();
done

2023-02-14 23:57 UTC, veriAjinkya commented on lib/include/libYulAST/YulIntrinsics.h
> +  }
Removed

2023-02-15 00:00 UTC, veriAjinkya commented on CMakeLists.txt
> +option(Y2L_ENABLE_DEBUG "Enable Debug" OFF)
It was a quick fix to add compile flag. This is removed now.

2023-02-15 00:01 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/FunctionCallHelper.h
> +  bool needsCast(std::string_view functionName);
removed

2023-02-15 00:01 UTC, veriAjinkya commented on lib/libYulAST/IntrinsicPatterns.cpp
> +  std::string typeStr(name);
will do it in a separate PR

2023-02-15 00:02 UTC, veriAjinkya commented on lib/libYulAST/YulIntrinsics.cpp
> +  addIntrinsic(intrinsicName, args, rets, YulIntrinsicId::AND);
done

2023-02-15 00:04 UTC, veriAjinkya commented on lib/include/libYulAST/Utils/ScopedSymbolTable.h
> +  Scope *currentScope;
done

2023-03-08 19:39 UTC, closed without merging