Aj/mem structs
Veridise/yul2llvm pull request #96
Opened 2023-04-18 22:27 UTC by veriAjinkya

This implements read and write from structs and memory. 
* read_from_mem and write_to_mem are moved from IntrinsicEmitter(pass1) to IntrinsicRewrite(pass2)
* Updated all testcases, the testsuite completely passes now
* Added helper function for getting gep indices from the distances added in yul to deref fields of structs

2023-04-21 00:14 UTC, Technius requested changes

2023-04-21 00:14 UTC, Technius commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +  intrinsics.addIntrinsic(funName, args, rets, YulIntrinsicId::ABI_DECODE);
Why are this and writeToMemory supposed to be ABI_DECODE intrinsics?

2023-04-21 19:20 UTC, veriAjinkya commented on tests/e2e/feature/dyn-types/bytes1.sol
> +//CHECK: %pyul_storage_var_load7 = load i8, i8 addrspace(1)* %"self->y_ptr", align 1
No these need to be exactly this to follow a naming convention

2023-04-21 19:21 UTC, veriAjinkya commented on tests/e2e/feature/structs/struct-storage2mem.sol
That is tested separtely in structs-mem-loacal and args, the point of this test is to check if ref is created properly

2023-05-03 11:04 UTC, veriAjinkya commented on tests/e2e/feature/structs/struct-storage2mem.sol
done

2023-05-03 11:06 UTC, veriAjinkya commented on tests/e2e/feature/structs/struct-storage-alias.sol
> +//CHECK: %"{{.*}}[[CONVERT]]->b->a_ptr" = getelementptr %"t_struct(St)12_storage", %"t_struct(St)12_storage" addrspace(1)* %"{{.*}}[[CONVERT]]", i32 0, i32 1
done

2023-05-03 11:08 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +          loadType, ptr, ptr->getName().substr(0, ptr->getName().size() - 4),
done

2023-05-03 11:11 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +llvm::Value *YulIntrinsicHelper::getPointerToStorageStructFieldFromRefrence(
done

2023-05-03 11:20 UTC, veriAjinkya commented on lib/libyul2llvm/YulASTVisitor/IntrinsicRewriter.cpp
> +  return ptr;
the calculations for memory are based on distance in bytes from starting address of struct while the calculation for storage structs are a search for slot offset.

2023-05-03 11:21 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  getFistAddInStorageStructDerefPattern(llvm::Instruction *i);
done

2023-05-03 11:21 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  getFistGEPInStorageStructDerefPattern(llvm::CallInst *i,
done

2023-05-03 11:21 UTC, veriAjinkya commented on lib/include/libyul2llvm/YulASTVisitor/IntrinsicHelper.h
> +  getFistGEPInMemoryStructDerefPattern(llvm::CallInst *i,
done

2023-05-03 11:23 UTC, veriAjinkya commented on lib/libYulAST/Types/YulFunctionSignature.cpp
> +  if (i = arguments.size() && i != o.arguments.size()) {
done

2023-05-03 11:47 UTC, veriAjinkya commented on lib/libYulAST/Types/YulFunctionSignature.cpp
> +                    "var_" + arguments[i]->name)) {
This is used to find a signature for a function, 
1. when types are not inferred or
2. when types are being inferred. 

This search is triggered only after function names are compared in caller. 
Though I agree function should name should be compared aswell. Fixed it

2023-05-03 11:48 UTC, veriAjinkya commented on lib/libYulAST/Types/YulTypeContext.cpp
> +      if (distance % 32 != 0)
done

2023-05-03 11:48 UTC, veriAjinkya commented on lib/libYulAST/Utils/FunctionSigVisitor.cpp
> +  intrinsics.addIntrinsic(funName, args, rets, YulIntrinsicId::ABI_DECODE);
It was a mistake, fixed it

2023-05-06 02:06 UTC, veriAjinkya commented on lib/libYulAST/Types/YulFunctionSignature.cpp
> +                    "var_" + arguments[i]->name)) {
This is called from `convertAbiFunNamesToYulNamesInFunSigs`. 
The function names in ABI are the names of functions in solidity. While in yul the names of functions are fun_<name_in_solidity>_<astId>. 
So the name of the function in `FunctionSignature` and in `YulFunctionDefinitionNode` are not going to match.

2023-05-06 02:10 UTC, veriAjinkya commented on lib/libYulAST/Types/YulFunctionSignature.cpp
> +                    "var_" + arguments[i]->name)) {
This also works in polymorphic cases because, there is a naming pattern in arguments in ABI and in Yul. 

Arguments names in ABI are suffixed with the their type.
Argument names in yul are var_<name in abi>
Note <name in abi> has type info

2023-05-06 02:10 UTC, veriAjinkya commented on lib/libYulAST/Types/YulFunctionSignature.cpp
> +                    "var_" + arguments[i]->name)) {
Changing it from operator to has same arguments. Adding docs

2023-05-08 18:36 UTC, merged